# **Introduction to Fourier transform in two dimensions**
### **Author: Dr. Rahul Remanan**

In [1]:
import os, math, time, numpy as np, scipy as sp, \
       matplotlib.image as mpimg, matplotlib.pyplot as plt

from scipy.stats import norm
from functools import cache, reduce

# Handling complex numbers in NumPy:

Every non-zero complex number ${z = x+ iy}$ can be written in the form: ${re}^{iθ}$, where the value: ${r = |z| = {\sqrt{{x^{2}+y^{2}}}}}$ is referred to as the **magnitude** of $z$, and $θ$ as the **phase, angle, or argument** of $z$.

## Getting the magnitude of a complex number array:

In [2]:
print(
    '\n',
    'Magnitude: ', np.abs([1.0, 1.0j, 1+1j, -1-1j])
)


 Magnitude:  [1.         1.         1.41421356 1.41421356]


## Getting the phase of a complex number array:

In [3]:
print(
    '\n',
    'In radians: ', np.angle([1.0, 1.0j, 1+1j, -1-1j]),
    '\n',
    'In degrees: ', np.angle([1.0, 1.0j, 1+1j, -1-1j], deg=True),
    '\n',
    np.angle([0., -0., complex(0., -0.), complex(-0., -0.)])   # convention
)


 In radians:  [ 0.          1.57079633  0.78539816 -2.35619449] 
 In degrees:  [   0.   90.   45. -135.] 
 [ 0.          3.14159265 -0.         -3.14159265]


## Getting the sign of a complex number array:

The [sign function](https://numpy.org/doc/stable/reference/generated/numpy.sign.html) is defined as: $S(x + iy) = \frac{(x + iy)}{\sqrt{x^2+y^2}}$

In [4]:
np.sign([1.0, 1.0j, 1+1j, -1-1j])

array([ 1.        +0.j        ,  0.        +1.j        ,
        0.70710678+0.70710678j, -0.70710678-0.70710678j])

## Separating real and imaginary parts of a complex number array:

In [267]:
c = 5 + (6*1j)
print(f'For the complex number: {c} the real component is: {c.real} and the imaginary component is: {c.imag} ...')

For the complex number: (5+6j) the real component is: 5.0 and the imaginary component is: 6.0 ...


# Discrete Fourier transform (DFT) and inverse discrete Fourier transform (iDFT):

In [243]:
# a = np.array(
#         [
#             [0.0, 0.5, 1.0],
#             [1.0, 2.0, 3.0],
#             [5.0, 7.0, 8.0],
#             [4.0, 9.0, 6.0]
#         ]
# )
a = np.random.uniform(0, 1, (3, 3))
print(a)
#a = np.expand_dims(a.flatten(), axis=-1)
#a = a.reshape(4, 5)
print(a)

[[0.98331832 0.96767458 0.74500893]
 [0.50398452 0.84573605 0.45241961]
 [0.70785722 0.16300844 0.24185947]]
[[0.98331832 0.96767458 0.74500893]
 [0.50398452 0.84573605 0.45241961]
 [0.70785722 0.16300844 0.24185947]]


In [244]:
a = np.insert(a, 0, 0, axis=0)
a = np.insert(a, 0, 0, axis=1)
print(a)

[[0.         0.         0.         0.        ]
 [0.         0.98331832 0.96767458 0.74500893]
 [0.         0.50398452 0.84573605 0.45241961]
 [0.         0.70785722 0.16300844 0.24185947]]


In [245]:
N = np.prod(a.shape)

## **Discrete Fourier transform:**

Discrete Fourier transform of a two dimensional $M{\times}N$ matrix, decomposes each value of the matrix: $r_{n}{\text{, where: }}r{\in}{ℝ}$,  into the form: ${c_{n}} = {a_{n}}({cos}({\theta}_{n}) + {i}{\cdot}{sin}({\theta}_{n}))$, through the application of: 
* [Euler's formula](https://en.wikipedia.org/wiki/Euler's_formula): ${e^{i{\cdot}{x}}={{\cos{x}}+{i}{\cdot}{\sin{x}}}}$
* [Improper Reimann integral](https://en.wikipedia.org/wiki/Improper_integral).

${F(a,b)={{\sum\limits_{k=0}^{N-1}}{\sum\limits_{l=0}^{M-1}}}f(k,l){e^{{-i}{2}{\pi}{({\frac{ka}{N}}+{\frac{lb}{M}})}}}}$

In [246]:
s = time.time()

In [247]:
e = time.time()

In [248]:
e - s 

0.20238137245178223

In [249]:
def fourier_transform_exp(d):
    e_ft = np.exp(-1 * (np.array([0 + 1j]) * 2 * math.pi * d))
    return e_ft.astype(np.complex128)

fourier_sum_list = []
fourier_coeff_list = []

def ft_cache(k, l, i, j):
    return ft_cache(k-1, l-1, i, j)

def compute_fourier_transform(inp_arr, verbose=False):
    assert len(inp_arr.shape) == 2, f'Expected a two dimensional input array, instead received an array of: {inp_arr.shape}  dimensions ...'
    N, M = inp_arr.shape[0], inp_arr.shape[1]
    a_ft = np.zeros_like(inp_arr).astype(np.complex128)
    prog_idx = 0
    fourier_dict = dict()

    fi_list = []
    for i in range(a_ft.shape[0]):
        fj_list = []
        for j in range(a_ft.shape[1]):
            start_time = time.time()
            prog_idx += 1
            f_sum = 0
            k_list = []
            for k in range(N):
                l_list = []
                for l in range(M):
                    d = ((k * i / N) + (l * j / M))
                    d = d - math.floor(d)

                    f_val = inp_arr[k, l] * np.array([1 + 0j])

                    if d == 0:
                        a_ft[i, j] += f_val
                    else:
                        try:
                            f_val *= fourier_dict[d]
                            a_ft[i, j] += f_val
                        except Exception as e:
                            fourier_dict.update({d : fourier_transform_exp(d)})
                            if verbose: print(e, len(fourier_dict), end = '\r', flush=True)
                            f_val *= fourier_dict[d]
                            a_ft[i, j] += f_val

                    l_list.append(
                        f_val #d
                    )
                    
                    f_sum += f_val

                k_list.append(l_list)
            
            fourier_coeff_list.append(k_list)
            fj_list.append(f_sum)

            prog_frac = prog_idx / (N * M)
            end_time = time.time()

            print(prog_frac, (end_time - start_time) * (1 - prog_frac) * N * M, end = '\r', flush=True)

        fi_list.append(fj_list)

    fourier_sum_list.append(fi_list)

    return a_ft

In [250]:
a_ft = compute_fourier_transform(a)

C:\Users\Rahul Remanan\AppData\Local\Temp\ipykernel_11392\1666121849.py:35: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  a_ft[i, j] += f_val
C:\Users\Rahul Remanan\AppData\Local\Temp\ipykernel_11392\1666121849.py:44: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  a_ft[i, j] += f_val
C:\Users\Rahul Remanan\AppData\Local\Temp\ipykernel_11392\1666121849.py:39: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  a_ft[i, j] += f_val


In [251]:
np.array(fourier_sum_list) / np.array(fourier_sum_list)[0][0][0]

array([[[[ 1.        +0.00000000e+00j],
         [-0.35224842-1.34715727e-01j],
         [-0.29550317-7.93266904e-17j],
         [-0.35224842+1.34715727e-01j]],

        [[-0.32118746-2.82180394e-01j],
         [ 0.19131168+1.52602268e-01j],
         [ 0.01972388-4.64377092e-03j],
         [ 0.1101519 +1.34221897e-01j]],

        [[-0.35762507-8.31305601e-17j],
         [ 0.05078483+1.16335356e-01j],
         [ 0.2560554 -4.55534684e-17j],
         [ 0.05078483-1.16335356e-01j]],

        [[-0.32118746+2.82180394e-01j],
         [ 0.1101519 -1.34221897e-01j],
         [ 0.01972388+4.64377092e-03j],
         [ 0.19131168-1.52602268e-01j]]]])

In [252]:
(1 - math.pow(0.25489486 * 2, 2)) / 2

0.37005722069116076

In [253]:
(math.pow(0.25489486, 2) + math.pow(0.44149085, 2))

0.2598855602881421

In [254]:
print(0.48464844 * 2, 0.44149085 * 2)

0.96929688 0.8829817


In [255]:
math.pow(1/2, 0.25489486)

0.8380482072961831

In [256]:
0.35674182 * 2

0.71348364

In [257]:
math.exp(-(0.25489486 / 0.44149085) * math.exp(1) * 2 + math.pi)

1.0027950752109094

In [258]:
0.25489486 / (math.pi / (2*math.exp(1))) 

0.44109860348310015

In [259]:
(math.acos((((0.25489486 / 0.44149085)))/ (2 * math.pi)) / (2 * math.pi)) * 360

84.72775975709463

In [260]:
math.pow(math.log(10), (0.25489486 / 0.44149085))

1.6185470348262552

In [261]:
(0.35674182 / 0.61789495) * math.exp(math.pi / 4)

1.2662908429175086

In [262]:
math.log(2) - (0.48464844 / 0.83943572)

0.11579691007109827

In [263]:
math.exp((0.48464844 + 0.83943572))

3.7587413724735894

In [264]:
1 / ((1 / (math.exp(1) * 2 / math.pi)) / 0.48464844)

0.8386899212650387

In [265]:
fourier_coeff_list

[[[array([0.+0.j]), array([0.+0.j]), array([0.+0.j]), array([0.+0.j])],
  [array([0.+0.j]),
   array([0.98331832+0.j]),
   array([0.96767458+0.j]),
   array([0.74500893+0.j])],
  [array([0.+0.j]),
   array([0.50398452+0.j]),
   array([0.84573605+0.j]),
   array([0.45241961+0.j])],
  [array([0.+0.j]),
   array([0.70785722+0.j]),
   array([0.16300844+0.j]),
   array([0.24185947+0.j])]],
 [[array([0.+0.j]), array([0.+0.j]), array([0.-0.j]), array([-0.+0.j])],
  [array([0.+0.j]),
   array([6.02108818e-17-0.98331832j]),
   array([-0.96767458-1.18505957e-16j]),
   array([-1.36855921e-16+0.74500893j])],
  [array([0.+0.j]),
   array([3.08601515e-17-0.50398452j]),
   array([-0.84573605-1.03572795e-16j]),
   array([-8.3108134e-17+0.45241961j])],
  [array([0.+0.j]),
   array([4.3343754e-17-0.70785722j]),
   array([-0.16300844-1.9962776e-17j]),
   array([-4.44288647e-17+0.24185947j])]],
 [[array([0.+0.j]), array([0.-0.j]), array([0.+0.j]), array([0.-0.j])],
  [array([0.+0.j]),
   array([-0.9833183

In [33]:
0.18303613 * 8 +

16.420478241099175

In [31]:
a_ft

array([[ 3.00554079+0.00000000e+00j, -0.59712129-6.49969487e-01j,
         0.49976608-1.53434449e-16j, -0.59712129+6.49969487e-01j],
       [-0.56907255-2.18881939e-16j,  0.26336827-5.46898626e-01j,
        -0.80443922-2.33293991e-16j,  0.26336827+5.46898626e-01j]])

In [14]:
for f in fourier_sum_list:
    for fl in f:
        print(fl)

[array([1.9784647+0.j]), array([0.42200884+0.72090944j]), array([-0.28198719-1.38412758e-16j]), array([0.42200884-0.72090944j])]


In [15]:
cos_arr, sin_arr = [], []
for idx, s in enumerate(fourier_sum_list):
    if idx == 0:
        n = s.real
    sqn = math.pow(math.pow(s.real, 2) + math.pow(s.imag, 2), 1 / 2)
    print(s, math.acos(s.real / sqn) / math.pi + abs(math.asin(s.imag / sqn) / math.pi))
    cos_arr.append(math.acos(s.real / sqn)); sin_arr.append(math.asin(s.imag / sqn))

AttributeError: 'list' object has no attribute 'real'

In [46]:
print()

In [47]:
fcl = []
for f in fourier_coeff_list:
    fcl.append(np.array(f))

In [55]:
fourier_coeff_list

[[[0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]],
 [[0.0, 0.25, 0.5, 0.75], [0.0, 0.25, 0.5, 0.75], [0.0, 0.25, 0.5, 0.75]],
 [[0.0, 0.5, 0.0, 0.5], [0.0, 0.5, 0.0, 0.5], [0.0, 0.5, 0.0, 0.5]],
 [[0.0, 0.75, 0.5, 0.25], [0.0, 0.75, 0.5, 0.25], [0.0, 0.75, 0.5, 0.25]],
 [[0.0, 0.0, 0.0, 0.0],
  [0.3333333333333333,
   0.3333333333333333,
   0.3333333333333333,
   0.3333333333333333],
  [0.6666666666666666,
   0.6666666666666666,
   0.6666666666666666,
   0.6666666666666666]],
 [[0.0, 0.25, 0.5, 0.75],
  [0.3333333333333333,
   0.5833333333333333,
   0.8333333333333333,
   0.08333333333333326],
  [0.6666666666666666,
   0.9166666666666666,
   0.16666666666666652,
   0.4166666666666665]],
 [[0.0, 0.5, 0.0, 0.5],
  [0.3333333333333333,
   0.8333333333333333,
   0.33333333333333326,
   0.8333333333333333],
  [0.6666666666666666,
   0.16666666666666652,
   0.6666666666666665,
   0.16666666666666652]],
 [[0.0, 0.75, 0.5, 0.25],
  [0.3333333333333333,
   0.08333333333333326,

In [54]:
print(f'\nFourier transform output: \n{a_ft}')


Fourier transform output: 
[[ 5.68433364+0.00000000e+00j  0.4806197 -1.34293115e+00j
   0.58955223-3.11965387e-16j  0.4806197 +1.34293115e+00j]
 [ 0.6929304 -3.46422312e-01j -0.1393641 -1.15491711e+00j
   0.22831675+3.60923288e-01j -0.39188728-6.74132278e-01j]
 [ 0.6929304 +3.46422312e-01j -0.39188728+6.74132278e-01j
   0.22831675-3.60923288e-01j -0.1393641 +1.15491711e+00j]]


## **Inverse discrete Fourier transform:**

Inverse discrete Fourier transform of a two dimensional $M{\times}N$ matrix, recomposes each value of the matrix: ${{c_{n}}{\text{, where: c}}{\in}{ℂ}}$, into the corresponding value: ${r_{n}}{\text{, where: r}}{{\in}ℝ}$, of another $M{\times}N$ matrix; which was used to derive the discrete Fourier transformed complex matrix. 

The inverse discrete Fourier transform function maps: ${c_{n}{\rightarrow}r_{n}}$, through the application of:
* [Euler's formula](https://en.wikipedia.org/wiki/Euler's_formula): ${e^{i{\cdot}{x}}={{\cos{x}}+{i}{\cdot}{\sin{x}}}}$
* [Improper Reimann integral](https://en.wikipedia.org/wiki/Improper_integral).

${f(x,y)={{\frac{1}{N{\cdot}M}}{\sum\limits_{k=0}^{N-1}}{\sum\limits_{l=0}^{M-1}}}F(k,l){e^{{i}{2}{\pi}{({\frac{kx}{N}}+{\frac{ly}{M}})}}}}$

In [ ]:
def inverse_fourier_transform_exp(d):
    e_ift = np.exp(np.array([0 + 1j]) * 2 * math.pi * d)
    return e_ift.astype(np.complex128)

def compute_inverse_fourier_transform(inp_arr):
    assert len(inp_arr.shape) == 2, f'Expected a two dimensional input array, instead received an array of: {inp_arr.shape}  dimensions ...'
    N, M = inp_arr.shape[0], inp_arr.shape[1]
    a_ift = np.zeros_like(inp_arr).astype(np.complex128)
    inverse_fourier_dict = dict()
    for i in range(a_ift.shape[0]):
        for j in range(a_ift.shape[1]):
            for k in range(N):
                for l in range(M):
                    d    = ((k * i) / N) + ((l * j) / M)
                    try:
                        a_ift[i, j] += inp_arr[k, l] * inverse_fourier_dict[d]
                    except Exception as e:
                        inverse_fourier_dict.update(
                            {d : inverse_fourier_transform_exp(d)}
                        )
                        print(e, len(inverse_fourier_dict), end = '\r', flush=True)
                        a_ift[i, j] += inp_arr[k, l] * inverse_fourier_dict[d]
    return a_ift / np.prod(inp_arr.shape)

In [ ]:
a_ift = compute_inverse_fourier_transform(a_ft)

In [ ]:
print(f'\nInverse Fourier transform output: \n{a_ift}')

## **Error in estimating the original input matrix using inverse discrete Fourier transform:**

In [ ]:
print(f'\nError between original 2D matrix input and inverse Fourier transform matrix: \n{np.expand_dims(a_ift.flatten(),-1) - a}')

# Separable functions of discrete Fourier transform:

$
\text{The discrete Fourier transform function: }
$

$
{F(a,b)={{\sum\limits_{k=0}^{N-1}}{\sum\limits_{l=0}^{M-1}}}f(k,l){e^{{-i}{2}{\pi}{({\frac{ka}{N}}+{\frac{lb}{M}})}}}}
\text{, can be expressed as two separable functions:}$

${P(a,l)={{\sum\limits_{k=0}^{N-1}}}f(k,l){e^{{-i}{2}{\pi}{({\frac{ka}{N}})}}}}$

${F(a,b)={{\sum\limits_{l=0}^{M-1}}}P(a,l){e^{{-i}{2}{\pi}{({\frac{lb}{M}})}}}}$

In [ ]:
def p_fourier_transform_sep(inp_arr, i, l):
    N = inp_arr.shape[0]
    p_ft = 0
    p_ft_dict = dict()
    for k in range(N):
        d = ((k * i) / N)
        d = d - math.floor(d)
        try:
            p_ft += inp_arr[k, l] * p_ft_dict[d]
        except:
            p_ft_dict.update(
                {d : fourier_transform_exp(d)}
            )
            p_ft += inp_arr[k, l] * p_ft_dict[d]
    return p_ft

def fourier_transform_sep(inp_arr, i, j):
    M = inp_arr.shape[1]
    ft = 0
    ft_dict = dict()
    for l in range(M):
        d = ((l * j) / M)
        d = d - math.floor(d)
        try:
            ft += p_fourier_transform_sep(inp_arr, i, l) * ft_dict[d]
        except:
            ft_dict.update(
                {d : fourier_transform_exp(d)}
            )
            ft += p_fourier_transform_sep(inp_arr, i, l) * ft_dict[d]
    return ft

def compute_fourier_transform_sep(inp_arr):
    assert len(inp_arr.shape) == 2, f'Expected a two dimensional input array, instead received an array of: {inp_arr.shape}  dimensions ...'
    a_ft_sep = np.zeros_like(inp_arr).astype(np.complex128)
    N, M = a_ft_sep.shape[0], a_ft_sep.shape[1]
    for i in range(N):
        for j in range(M):
            a_ft_sep[i, j] = fourier_transform_sep(inp_arr, i, j)[0]
    return a_ft_sep

In [ ]:
a_ft_sep = compute_fourier_transform_sep(a)

In [ ]:
print(f'\nOutput of the Fourier transform using separable functions: \n{a_ft_sep}')

## **Difference in results using two methods of evaluating discrete Fourier transform:**

In [ ]:
a_ft - a_ft_sep

# Separable functions of inverse discrete Fourier transform:

$
\text{The inverse discrete Fourier transform function: }
$

$
{f(x,y)={{\frac{1}{N{\cdot}M}}{\sum\limits_{k=0}^{N-1}}{\sum\limits_{l=0}^{M-1}}}F(k,l){e^{{i}{2}{\pi}{({\frac{kx}{N}}+{\frac{ly}{M}})}}}}
\text{, can be expressed as two separable functions:}$

${p(x,l)={{\frac{1}{N}}{\sum\limits_{k=0}^{N-1}}}F(k,l){e^{{i}{2}{\pi}{({\frac{kx}{N}})}}}}$

${f(x,y)={{\frac{1}{M}}{{\sum\limits_{l=0}^{M-1}}}}p(x,l){e^{{i}{2}{\pi}{({\frac{ly}{M}})}}}}$

In [ ]:
def p_inverse_fourier_transform_sep(inp_arr, i, l):
    N = inp_arr.shape[0]
    p_ift = 0
    for k in range(N):
        d      = ((k * i) / N)
        p_ift += inp_arr[k, l] * inverse_fourier_transform_exp(d)
    return p_ift / N

def inverse_fourier_transform_sep(inp_arr, i, j):
    M = inp_arr.shape[1]
    ift = 0
    for l in range(M):
        d    = ((l * j) / M)
        ift += p_inverse_fourier_transform_sep(inp_arr, i, l) * inverse_fourier_transform_exp(d)
    return ift / M

def compute_inverse_fourier_transform_sep(inp_arr):
    assert len(inp_arr.shape) == 2, f'Expected a two dimensional input array, instead received an array of: {inp_arr.shape}  dimensions ...'
    N, M = inp_arr.shape[0], inp_arr.shape[1]
    a_ift_sep = np.zeros_like(inp_arr).astype(np.complex128)
    for i in range(N):
        for j in range(M):
            a_ift_sep[i, j] = inverse_fourier_transform_sep(inp_arr, i, j)[0]
    return a_ift_sep

In [ ]:
a_ift_sep = compute_inverse_fourier_transform_sep(a_ft_sep)

In [ ]:
print(f'\nOutput of the inverse Fourier transform using separable functions: \n{a_ift_sep}')

## **Error in estimating the original input matrix using inverse discrete Fourier transform:**

In [ ]:
a_ift_sep - a

# Fourier transform of a discrete signal using NumPy:

In [ ]:
# Source - https://stackoverflow.com/q/52350774
# Posted by Luke Polson
# Retrieved 2026-04-03, License - CC BY-SA 4.0

# Sample spacing
dx = 1.0 / 1000.0

# Points
x1 = -5
x2 = 5

x = np.arange(x1, x2, dx)

def light_intensity():
    return 10 * sp.stats.norm.pdf(x, 0, 1)+ 0.1 * np.random.randn(x.size)

fig, ax = plt.subplots()
ax.plot(x,light_intensity())

In [ ]:
# Source - https://stackoverflow.com/a/52351218
# Posted by Mateen Ulhaq, modified by community. See post 'Timeline' for change history
# Retrieved 2026-04-03, License - CC BY-SA 4.0
# Modified by Dr. Rahul Remanan after retrieval

def norm_fft(y, T, max_freq=None):
    N = y.shape[0]
    Nf = N // 2 if max_freq is None else int(max_freq * T)
    xf = np.linspace(0.0, 0.5 * N / T, N // 2)
    yf = 2.0 / N * np.fft.fft(y)
    return xf[:Nf], yf[:Nf]

def generate_signal(x, signal_gain=10.0, noise_gain=0.0):
    signal = norm.pdf(x, 0, 1)
    noise = np.random.randn(x.size)
    return signal_gain * signal + noise_gain * noise

# Signal parameters
x1 = 0.0
x2 = 5.0
N = 10000
T = x2 - x1

# Generate signal data
x = np.linspace(x1, x2, N)
y = generate_signal(x)

# Apply FFT
xf, yf = norm_fft(y, T, T / np.pi)

# Plot
fig, ax = plt.subplots(2)
ax[0].plot(x, y)
ax[1].plot(xf, np.abs(yf))
plt.show()

In [ ]:
# Source - https://stackoverflow.com/a/52351218
# Posted by Mateen Ulhaq, modified by community. See post 'Timeline' for change history
# Retrieved 2026-04-03, License - CC BY-SA 4.0
# Modified by Dr. Rahul Remanan after retrieval

def norm_sym_fft(y, T, max_freq=None):
    N = y.shape[0]
    b = N if max_freq is None else int(max_freq * T + N // 2)
    a = N - b
    xf = np.linspace(-0.5 * N / T, 0.5 * N / T, N)
    yf = 2.0 / N * np.fft.fftshift(np.fft.fft(y))
    return xf[a:b], yf[a:b]

def generate_signal(x, signal_gain=10.0, noise_gain=0.0):
    signal = norm.pdf(x, 0, 1)
    noise = np.random.randn(x.size)
    return signal_gain * signal + noise_gain * noise

# Signal parameters
x1 = -10.0
x2 = 10.0
N = 10000
T = x2 - x1

# Generate signal data
x = np.linspace(x1, x2, N)
y = generate_signal(x)

# Apply FFT
xf, yf = norm_sym_fft(y, T, 4 / np.pi)

# Plot
fig, ax = plt.subplots(2)
ax[0].plot(x, y)
ax[1].plot(xf, np.abs(yf))
plt.show()

In [ ]:
# Source - https://stackoverflow.com/a/52351212
# Posted by Mahdi
# Retrieved 2026-04-03, License - CC BY-SA 4.0
# Modified by Dr. Rahul Remanan after retrieval

# Sample spacing
dx = 1.0 / 1000.0

# Points
x1 = -5
x2 = 5

x = np.arange(x1, x2, dx)

xf = np.arange(x1, x2, dx)
yf = np.fft.fft(light_intensity())
yfft = np.fft.fftshift(np.abs(yf))
fig,ax = plt.subplots(1, 2, figsize=(10, 5))
ax[0].plot(xf, light_intensity())
ax[1].plot(xf, yfft)
ax[1].set_xlim(-0.05, 0.05)
plt.show()

# [Fast Fourier transform of a grey scale image](https://homepages.inf.ed.ac.uk/rbf/HIPR2/fourier.htm):

In [ ]:
img_file = '../media/cln1.gif'
if not os.path.exists(img_file):
    !curl https://homepages.inf.ed.ac.uk/rbf/HIPR2/images/cln1.gif >> {img_file}

In [ ]:
img = mpimg.imread(img_file)

In [ ]:
imgplot = plt.imshow(
    np.expand_dims(
        img[ : , : , 0], axis=-1
    )
)

In [ ]:
img_compute_fft = compute_fourier_transform(img[:, :, 0])

In [ ]:
img_fft = np.fft.fft(

    img[ : , : , 0]

)

In [ ]:
print(f'\nOutput of the fast Fourier transformed grey scale image: \n{img_fft}')

In [ ]:
np.max(np.abs(img_fft)), np.min(np.abs(img_fft))

In [ ]:
def min_max_scaler(img):
    if np.max(img) - np.min(img) != 0:
        return (img - np.min(img)) / (np.max(img) - np.min(img))
    return img

def log_transform(img):
    return (1 / (np.log(1 + np.max(img)))) * np.log(1 + img)

In [ ]:
img_fft_mag_plot = plt.imshow(
    np.expand_dims(
        log_transform(
            (
                np.abs(
                    img_compute_fft
                )
            )
        ), axis=-1
    )
)

In [ ]:
img_fft_phase_plot = plt.imshow(
    np.expand_dims(
        log_transform(
            min_max_scaler(
                np.angle(
                    img_fft
                )
            )
        ), axis=-1
    )
)

# Inverse fast Fourier transform:

In [ ]:
img_ifft = np.fft.ifft(

    img_fft

)

In [ ]:
img_fft_mag_plot = plt.imshow(
    np.abs(
        np.expand_dims(
            img_ifft, axis=-1
        )
    )
)

## Inverse Fourier transform without the phase information:

In [ ]:
img_ifft_mag_plot = plt.imshow(
    np.expand_dims(
        log_transform(
            np.abs(
                np.fft.ifft(
                    np.abs(
                        img_fft
                    )
                )
            )
        ), axis=-1
    )
)

## Inverse Fourier transform using magnitude and phase as separable components:

In [ ]:
img_ifft_mag_plot = plt.imshow(
    np.expand_dims(
        min_max_scaler(
            np.abs(
                np.fft.ifft(
                    np.abs(
                        img_fft
                    ) * np.sign(
                            img_fft
                        )
                )
            )
        ), axis=-1
    )
)