In [1]:
import numpy as np
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
len (x)

20

In [2]:
x[0:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
x[1:9]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
x[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
from random import randint
n =(randint(0, len(x)//4))
x[n:(n+(len(x)*3//4))]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])