# Knuth-Morris-Pratt (KMP) string matching algorithm

A relatively efficient string matching algorithm, that executes with ```O(m + n)``` complexity, for a pattern string of length ```m``` matched with a given input string of length ```n```; where ```m <= n```.

In [1]:
input_string = 'ababcabcabababd'
comparison_string = 'aaabbaaaabd'

In [2]:
import numpy as np

## Compute Pi-table for string comparison

In [3]:
def compute_pi_table(input_string:str)->'NumPy array':
    pi_table = np.zeros(len(input_string))
    init_char = input_string[0]

    for i, pi_val in enumerate(pi_table):
        match_char = input_string[i]
        if i > 0 and pi_table[i - 1] > 0 and match_char == input_string[int(pi_table[i - 1])]:
            pi_table[i] = pi_table[i - 1] + 1
        elif i > 0 and init_char == match_char:
            pi_table[i] = 1

    return pi_table

In [4]:
print(comparison_string)

aaabbaaaabd


In [5]:
compute_pi_table(comparison_string)

array([0., 1., 2., 0., 0., 1., 2., 3., 1., 0., 0.])

In [6]:
compute_pi_table('aabadadaabeaabaaad')

array([0., 1., 0., 1., 0., 1., 0., 1., 2., 3., 0., 1., 2., 3., 4., 1., 2.,
       0.])

In [7]:
compute_pi_table('abcdabeabf')

array([0., 0., 0., 0., 1., 2., 0., 1., 2., 0.])

In [8]:
compute_pi_table('abcdeabfabcabc')

array([0., 0., 0., 0., 0., 1., 2., 0., 1., 2., 3., 1., 2., 3.])

In [9]:
compute_pi_table('aaab')

array([0., 1., 2., 0.])

In [10]:
compute_pi_table('abcdabeabf')

array([0., 0., 0., 0., 1., 2., 0., 1., 2., 0.])

In [11]:
compute_pi_table('abcdaabfabc')

array([0., 0., 0., 0., 1., 1., 2., 0., 1., 2., 3.])

In [12]:
compute_pi_table('aabcadaabe')

array([0., 1., 0., 0., 1., 0., 1., 2., 3., 0.])

In [13]:
compute_pi_table('aaabaacd')

array([0., 1., 2., 0., 1., 2., 0., 0.])

## Implementing Knuth-Morris-Pratt (KMP) string matching

In [14]:
def knuth_morris_pratt_string_match(input_string:str, comparison_string:str)->list:
    pi_table = compute_pi_table(comparison_string)
    i, j = 0, 0
    string_match_index = []

    for idx, char_string in enumerate(input_string):
        if input_string[i] == comparison_string[j]:
            i += 1
            j += 1
            if j + 1 == len(comparison_string):
                string_match_index.append(idx - len(comparison_string) + 1)
                j = 0
        else:
            if j > 0:
                j = int(pi_table[j - 1])
            else:
                j = 0

            if j == 0 and idx > 0:
                i += 1

    return string_match_index

In [15]:
match_indices = knuth_morris_pratt_string_match('aaabaaabcadaabeaabcadaabe', 'aabcadaabe')

In [16]:
for mi in match_indices:
    print('aaabaaabcadaabeaabcadaabe'[mi : mi + len('aabcadaabe')])

aabcadaabe
aabcadaabe
